"""empty message

Revision ID: 93a2a5372ddc
Revises: 
Create Date: 2019-12-10 15:08:50.318137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93a2a5372ddc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crimedate', sa.String(length=64), nullable=True),
    sa.Column('crimetime', sa.String(length=64), nullable=True),
    sa.Column('crimecode', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.Column('inside_outside', sa.String(length=64), nullable=True),
    sa.Column('weapon', sa.String(length=64), nullable=True),
    sa.Column('post', sa.String(length=64), nullable=True),
    sa.Column('district', sa.String(length=64), nullable=True),
    sa.Column('neighborhood', sa.String(length=64), nullable=True),
    sa.Column('longitude', sa.String(length=64), nullable=True),
    sa.Column('latitude', sa.String(length=64), nullable=True),
    sa.Column('premise', sa.String(length=64), nullable=True),
    sa.Column('total_incidents', sa.String(length=64), nullable=True),
    sa.Column('weekday', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crime_crimecode'), 'crime', ['crimecode'], unique=False)
    op.create_index(op.f('ix_crime_crimedate'), 'crime', ['crimedate'], unique=False)
    op.create_index(op.f('ix_crime_crimetime'), 'crime', ['crimetime'], unique=False)
    op.create_index(op.f('ix_crime_description'), 'crime', ['description'], unique=False)
    op.create_index(op.f('ix_crime_district'), 'crime', ['district'], unique=False)
    op.create_index(op.f('ix_crime_inside_outside'), 'crime', ['inside_outside'], unique=False)
    op.create_index(op.f('ix_crime_latitude'), 'crime', ['latitude'], unique=False)
    op.create_index(op.f('ix_crime_location'), 'crime', ['location'], unique=False)
    op.create_index(op.f('ix_crime_longitude'), 'crime', ['longitude'], unique=False)
    op.create_index(op.f('ix_crime_neighborhood'), 'crime', ['neighborhood'], unique=False)
    op.create_index(op.f('ix_crime_post'), 'crime', ['post'], unique=False)
    op.create_index(op.f('ix_crime_premise'), 'crime', ['premise'], unique=False)
    op.create_index(op.f('ix_crime_total_incidents'), 'crime', ['total_incidents'], unique=False)
    op.create_index(op.f('ix_crime_weapon'), 'crime', ['weapon'], unique=False)
    op.create_index(op.f('ix_crime_weekday'), 'crime', ['weekday'], unique=False)
    op.create_table('description',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_description_description'), 'description', ['description'], unique=False)
    op.create_table('district',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('district', sa.String(length=64), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_district_district'), 'district', ['district'], unique=False)
    op.create_table('neighborhood',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('neighborhood', sa.String(length=64), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_neighborhood_neighborhood'), 'neighborhood', ['neighborhood'], unique=False)
    op.create_table('premise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('premise', sa.String(length=64), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_premise_premise'), 'premise', ['premise'], unique=False)
    op.create_table('weapon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weapon', sa.String(length=64), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weapon_weapon'), 'weapon', ['weapon'], unique=False)
    op.create_table('weekday',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.String(length=64), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekday_weekday'), 'weekday', ['weekday'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weekday_weekday'), table_name='weekday')
    op.drop_table('weekday')
    op.drop_index(op.f('ix_weapon_weapon'), table_name='weapon')
    op.drop_table('weapon')
    op.drop_index(op.f('ix_premise_premise'), table_name='premise')
    op.drop_table('premise')
    op.drop_index(op.f('ix_neighborhood_neighborhood'), table_name='neighborhood')
    op.drop_table('neighborhood')
    op.drop_index(op.f('ix_district_district'), table_name='district')
    op.drop_table('district')
    op.drop_index(op.f('ix_description_description'), table_name='description')
    op.drop_table('description')
    op.drop_index(op.f('ix_crime_weekday'), table_name='crime')
    op.drop_index(op.f('ix_crime_weapon'), table_name='crime')
    op.drop_index(op.f('ix_crime_total_incidents'), table_name='crime')
    op.drop_index(op.f('ix_crime_premise'), table_name='crime')
    op.drop_index(op.f('ix_crime_post'), table_name='crime')
    op.drop_index(op.f('ix_crime_neighborhood'), table_name='crime')
    op.drop_index(op.f('ix_crime_longitude'), table_name='crime')
    op.drop_index(op.f('ix_crime_location'), table_name='crime')
    op.drop_index(op.f('ix_crime_latitude'), table_name='crime')
    op.drop_index(op.f('ix_crime_inside_outside'), table_name='crime')
    op.drop_index(op.f('ix_crime_district'), table_name='crime')
    op.drop_index(op.f('ix_crime_description'), table_name='crime')
    op.drop_index(op.f('ix_crime_crimetime'), table_name='crime')
    op.drop_index(op.f('ix_crime_crimedate'), table_name='crime')
    op.drop_index(op.f('ix_crime_crimecode'), table_name='crime')
    op.drop_table('crime')
    # ### end Alembic commands ###
